### PR TITLE
Add optional channel numbers on graphical epg 

### PR DESCRIPTION
**Pull request by davesayers2014**
UsageConfig.py also has reduce minimum picon width to 50 it helps with the gap when less then 4 digit channel numbers are used

### CODE REVIEW

**Comment by arn354** [comment]
Thx, trying probably tomorrow locally

**Comment by davesayers2014** [comment]
Ok I've seen another commit has been merged for UsageConfig.py should I include it in this request or leave it to be added if this is Merged?

**Comment by davesayers2014** [comment]
I've just seen there has been another pull request merged for UsageConfig.py should I include it in this request or leave it as it is to be added if it is merged?

**Comment by arn354** [comment]
Leave it for now, I did not find time to check. If it is still mergeable, no problem. The change will be there as only the git-diff will be applied not the full file

**Comment by arn354** [comment]
https://github.com/openatv/enigma2/commit/909f835f1b014f19aa35905387695c848845c73f - first crash to fix.

**Comment by hd75hd** [comment]
Great Job ..

i have a question ..
can you also add "Service Number & Picon" ?

**Comment by davesayers2014** [comment]
Just service number and picon without service name? I didn't think about it but can look at adding it. It would look odd if there wasn't a picon for one channel so you only had service number.

**Comment by hd75hd** [comment]
i don´t know how it looks only with number and picon but i think its ok.
If you think that looks not good you don´t add this
it was only a idea ;-)

sorry my english is not so good

**Comment by davesayers2014** [comment]
I'll look into it I just copied some of the code from vix to add channel numbers so I'll look at adding just channel numbers aswell as channel numbers and picons

**Comment by davesayers2014** [comment]
Ive tried adding service number and picon to line 886 in UsageConfig.py  config.epgselection.graph_servicetitle_mode = ConfigSelection(default = "servicename", choices = [("servicename", _("Service Name")), ("picon", _("Picon")), ("picon+servicename", _("Picon and Service Name")), ("servicenumber+servicename", _("Service Number and Service Name")), ("servicenumber+picon+servicename", _("Service Number, Picon and Service Name")), ("servicenumber+picon", _("Service Number and Picon")), ("servicenumber", _("Service Number"))]) the issue is that service number width needs adding to the menu on epg settings but im not sure of how to add it

**Comment by Schimmelreiter** [comment]
Number + Picon only should fall back to abbreviated channel name if no picon is found.

If a picon exists and it's a good one, the channel name is rather redundant, but it should be there if there is no picon.

**Comment by hd75hd** [comment]
It crash here ..

09:46:06.0633 { D } Traceback (most recent call last):
09:46:06.0635 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
09:46:06.0638 { D }   File "/usr/lib/enigma2/python/Screens/EpgSelection.py", line 646, in nextBouquet
09:46:06.0642 { D }   File "/usr/lib/enigma2/python/Screens/EpgSelection.py", line 619, in BouquetOK
09:46:06.0645 { D }   File "/usr/lib/enigma2/python/Components/EpgList.py", line 1397, in fillGraphEPG
09:46:06.0649 { D } TypeError: 'ServiceReference' object has no attribute '__getitem__'
09:46:06.0651 [ E ] python/python.cpp:209 call (PyObject_CallObject(<bound method HelpableActionMap.action of <Components.ActionMap.HelpableActionMap instance at 0x70a5d300>>,('EPGSelectActions', 'nextBouquet')) failed)

i think the problem is, if a Bouquet have Services with and without Picons ..

http://www.opena.tv/openatv-5-3-image-rueckmeldungen/30784-crash-bei-epg-seit-openatv-5-3-sogno8800hd-20161228_usb-zip.html

**Comment by arn354** [comment]
i reverted.
Graphical EPG is a combination of python and c++ parts. it is not not simply changing python parts. You also need to look into required c++ changes for list objects.
create an issue here so it does not get lost, once someone from atv finds time to add it completely.

**Comment by davesayers2014** [comment]
Line 1387

picon = None if piconIdx == 0 else serviceList[serviceIdx][piconIdx]
# We pass the serviceref if we don't have the channel number yet, so it can be grabbed
channel = serviceList[serviceIdx] if (channelIdx == None) else serviceList[serviceIdx][channelIdx]

Line 1396

channel = serviceList[serviceIdx] if (channelIdx == None) else serviceList[serviceIdx][channelIdx]

**Comment by davesayers2014** [comment]
No chance of this getting looked at? I've had it working with 6.0 but I can't seem to add the latest commits. I've included the the files here https://github.com/openatv/enigma2/issues/618 but would be nice to know if it wiill be looked at as it saves me having to me having to update the github branch if it's not going to be considered thanks

**Comment by davesayers2014** [comment]
I did manage to add the latest commits

**Comment by arn354** [comment]
i merged the last Pull Request - is that everything?
will see tomorrow in 6.2 .

**Comment by davesayers2014** [comment]
Pull request was for 6.2 there is different code for 6.1 in UsageConfig.py https://github.com/openatv/enigma2/commit/986ace9d93fe899a0f62f15f8844a8d93dd54e8e#diff-d7c03163c5c264700606df79f6eef93f I'll make a pull request for it later. 

There is this commit on Vix for optional alignment of numbers but I couldn't get it to work https://github.com/OpenViX/enigma2/commit/0fe174fa7a550add08532ecff90945d3f6f2a0dd#diff-b8b856a34e1cffe75195c252688fd2a1
